config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tweets#index"
  resources :tweets, only: [:index, :create, :destroy] do
    resources :likes, only: [:create, :destroy]
  end
  get 'users/search' => 'users/search#index'
  get 'users/search/find' => 'users/search#find'
  resources :users, only: :show do
    member do
      get :following, :followers
    end
    resources :likes, only: :index
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :tweet
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  validates :body, length: { maximum: 140 }

  def user_likes?(user)
    likes.where(user_id: user.id).present?
  end

  def json_tweet
    { id: id,
      body: body,
      created_at: created_at.to_s(:tweet),
      username: user.username,
      user_nickname: user.nickname,
      visible: user.visible?,
      user_id: user.id
    }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :nickname, presence: true, uniqueness: true,
                       length: { maximum: 20, minimum: 4 }
  validates :username, presence: true, uniqueness: true,
                       length: { maximum: 20, minimum: 4 }, format: { with: /\A[a-zA-Z\d\s.-]*\z/ }
  validates :email, presence: true, uniqueness: true,
                    length: { maximum: 100 }
  validates :password, presence: true,
                       length: { maximum: 8, minimum: 4 }, format: { with: /\A[a-zA-Z\d\s]*\z/ }
  validates :password_confirmation, presence: true,
                                    length: { maximum: 8, minimum: 4 }, format: { with: /\A[a-zA-Z\d\s]*\z/ }
  enum visibility: { visible: 0, hidden: 1 }
  has_many :tweets
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :followed, through: :active_relationships
  has_many :followers, through: :passive_relationships
  has_many :likes
  has_many :like_tweets, through: :likes, source: :tweet

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["username = :value", { :value => username }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    followed.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :username, :email, :visibility])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:nickname, :password])
  end

  def after_sign_in_path_for(resource)
    root_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.create(create_params)
    set_tweet
  end

  def destroy
    @like = current_user.likes.find_by(tweet_id: params[:tweet_id])
    @like.destroy
    set_tweet
  end

  def index
    @tweets = current_user.like_tweets.page(params[:page]).per(10).order("id DESC")
  end

  private
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end

  def create_params
    params.permit(:tweet_id).merge(user_id: current_user.id)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_to :back
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_to :back
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @user = current_user
    @tweets = Tweet.page(params[:page]).per(10).order("created_at DESC")
    @tweet = Tweet.new
    respond_to do |format|
      format.html { render :index }
      format.json {
        tweets = @tweets.map do |tweet|
          tweet.json_tweet
        end
        render json: tweets
      }
    end
  end

  def create
    tweet = Tweet.new(tweet_params)
    if tweet.save
      @tweets = Tweet.page(params[:page]).per(10).order("created_at DESC")
    else
      flash[:alert] = "140文字以上で入力してください   ※半角・全角問わず"
      redirect_to action: :index
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body).merge(user_id: current_user.id)
  end

end

app/controllers/users/search_controller.rb
class Users::SearchController < ApplicationController
  def index
    if params[:word]
      @users = User.where("concat(nickname, username) LIKE ?", "%#{params[:word]}%")
    else
      @users = User.all
    end
  end

  def find
    params[:word] == "" ? @users = []: @users = User.where("concat(nickname, username) LIKE ?", "%#{params[:word]}%")
    @all_users = User.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  def show
    @tweets = Tweet.page(params[:page]).where(user_id:params[:id]).per(10).order("created_at DESC")
  end

  def following
    @users = @user.followed
  end

  def followers
    @users = @user.followers
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.haml
.js-flash-message
  - flash.each do |key, value|
    %div{ class: 'alert alert-#{key}'}
      .container
        = value

app/views/layouts/_header.html.haml
%header
  .header-left
    = link_to image_tag('tweet-logo.jpg', { alt: 'ツイッター', class: "tweet-logo"}), root_path
  .header-right
    .item
      = link_to "ホーム", root_path
    .item
      = link_to "友達を検索", users_search_path
    .item
      - if current_user
        = link_to "ログアウト", destroy_user_session_path, method: :delete
      - else
        = link_to "ログイン", user_session_path

app/views/layouts/_profile.html.haml
= render partial: "layouts/profile_detail", locals: {user: current_user}
- if user != current_user
  %hr
  = render partial: "layouts/profile_detail", locals: {user: user}

app/views/layouts/_profile_detail.html.haml
.profile.clearfix
  .profile__avatar
    = image_tag("noimage.jpeg", class:"avatar")
  .profile__nickname
    = link_to user_path(user), class:"nickname" do
      = user.nickname
    @#{user.username}
    - if user.hidden?
      .fa.fa-key
    = render partial: "users/follow_form", locals: {user: user} if user != current_user
%table
  %tr
    %td
      = user.followers.count
    %td
      = user.followed.count
    %td
      = user.tweets.count
  %tr.profile-title
    %td.followed
      = link_to followers_user_path(user) do
        フォロー
        %br
        されている
    %td.following
      = link_to following_user_path(user) do
        フォロー
        %br
        している
    %td.num-of-tweets
      = link_to "投稿数", user_path(user)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Iwatter
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
  %body
    = render "layouts/flash"
    = render "layouts/header"
    = yield

app/views/likes/_like.html.haml
- if user_signed_in?
  - if tweet.user_likes?(current_user)
    = link_to tweet_like_path(tweet, tweet.likes.find_by(user_id: current_user.id).id), method: :delete, remote: true do
      .fa.fa-heart= tweet.likes.count
  - else
    = link_to tweet_likes_path(tweet), method: :post, remote: true do
      .fa.fa-heart-o
      - if tweet.likes.count != 0
        = tweet.likes.count

app/views/likes/create.js.haml
$("#tweets_#{@tweet.id}").html("#{j(render partial: '/likes/like', locals: {tweet: @tweet, like: @like})}")

app/views/likes/destroy.js.haml
$("#tweets_#{@tweet.id}").html("#{j(render partial: '/likes/like', locals: {tweet: @tweet})}")

app/views/likes/index.html.haml
.main
  .main-left
    = link_to "トップへ戻る", root_path
    = link_to "マイページに戻る", user_path(current_user)
    .tweet-home
      いいねしたツイート一覧
      .tweets
        = render partial: "tweets/tweet",collection: @tweets
      = paginate @tweets
  .main-right
    = render partial: "layouts/profile", locals: {user: current_user}

app/views/tweets/_tweet.html.haml
- if current_user
  - if (tweet.user.visible? && current_user.following?(tweet.user)) || tweet.user == current_user
    = render partial:"tweets/tweet_detail", locals: {tweet: tweet}
- else
  - if tweet.user.visible?
    = render partial:"tweets/tweet_detail", locals: {tweet: tweet}

app/views/tweets/_tweet_detail.html.haml
.tweet
  .tweet__account-name
    = link_to user_path(tweet.user), class:"nickname" do
      = tweet.user.nickname
    @#{tweet.user.username}
  .tweet__body
    = tweet.body
    .like_buttons{id: "tweets_#{tweet.id}"}
      = render partial: "likes/like", locals:{tweet: tweet}
  .tweet__time
    = tweet.created_at.to_s(:tweet)
  .tweet__right-button
    - if tweet.user == current_user
      = link_to tweet_path(tweet), method: :delete do
        %i.fa.fa-trash-o
    - else
      = render partial: "users/follow_form", locals: {user: tweet.user}

app/views/tweets/create.js.haml
$("#js-tweet").html("#{j(render @tweets)}");
$(".tweet-form").val("");

app/views/tweets/index.html.haml
.main
  .main-left
    - if current_user
      いまなにしてる？
      = form_for(@tweet, remote: true) do |f|
        = f.text_area :body, class: "tweet-form", size: "65×10", required: true
        = f.submit "ツイートする", class: "tweet-submit"
    .tweet-home
      ホーム
      .tweets#js-tweet
        = render @tweets
      = paginate @tweets
  - if current_user
    .main-right
      = render partial: "layouts/profile", locals: {user: current_user}

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build) do |f|
  = hidden_field_tag :followed_id, user.id
  = f.submit "フォローする", class: "btn btn-primary js-follow"

app/views/users/_follow_form.html.haml
- if current_user
  #follow_form
  - if current_user.following?(user)
    = render partial: 'users/unfollow', locals: {user: user}
  - else
    = render partial: 'users/follow', locals: {user: user}

app/views/users/_tweet.html.haml
- if (tweet.user.visible? || current_user.following?(tweet.user)) || tweet.user == current_user
  .tweet
    .tweet__body
      = tweet.body
      .like_buttons{id: "tweets_#{tweet.id}"}
        = render partial: "likes/like", locals:{tweet: tweet}
    .tweet__time
      = tweet.created_at.to_s(:tweet)
    .tweet__right-button
      - if tweet.user == current_user
        = link_to tweet_path(tweet), method: :delete do
          %i.fa.fa-trash-o

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: user.id),
             html: { method: :delete }) do |f|
  = f.submit "フォローをやめる", class: "btn js-unfollow"

app/views/users/_user.html.haml
.tweet
  .tweet__body
    = link_to user.nickname, user_path(user)
    @#{user.username}
    - if user.hidden?
      .fa.fa-key
  .tweet__time
    = user.tweets.last.try(:body)
  .tweet__follow-button
    = render partial: "users/follow_form", locals: {user: user} if current_user

app/views/users/followers.html.haml
.main
  .main-left
    = link_to "トップへ戻る", root_path
    |
    = link_to "#{@user.nickname}さんがフォローしているアカウントを見る", following_user_path(@user)
    .tweet-home
      #{@user.nickname}さんは#{@user.followed.count}人にフォローされています
    = render partial: "users/user", collection: @users
  .main-right
    = render partial: "layouts/profile", locals: {user: @user}

app/views/users/following.html.haml
.main
  .main-left
    = link_to "トップへ戻る", root_path
    |
    = link_to "#{@user.nickname}さんのフォロワーを見る", followers_user_path(@user)
    .tweet-home
      #{@user.nickname}さんは#{@user.followed.count}人をフォローしています
    = render partial: "users/user", collection: @users
  .main-right
    = render partial: "layouts/profile", locals: {user: @user}

app/views/users/search/find.html.haml
.main
  .main-left
    - if current_user
      友人を検索してみよう
      = form_tag(users_search_find_path, method: :get) do
        = text_field :"", :word, class: "tweet-form", placeholder: "キーワード"
        = submit_tag "再検索する"
    - if @users == []
      %p.non-user
        該当するユーザーはいません。
      %p
        ↓ユーザー一覧↓
      = render partial: "users/user", collection: @all_users
    - else
      = render partial: "users/user", collection: @users

app/views/users/search/index.html.haml
.main
  .main-left
    - if current_user
      友人を検索してみよう
      = form_tag(users_search_path, method: :get) do
        = text_field :"", :word, class: "tweet-form", placeholder: "キーワード"
        = submit_tag "検索する"
    = render partial: "users/user", collection: @users

app/views/users/show.html.haml
.main
  .main-left
    = link_to "トップへ戻る", root_path
    = link_to "いいねしたツイート", user_likes_path(current_user)
    .tweet-home
      = @user == current_user ? "あなたのツイート": "#{@user.nickname}さんのツイート"
      .tweets
        - if (@user.hidden? && !(current_user.following?(@user))) && @user != current_user
          このアカウントは非公開です
        - else
          = render partial: "users/tweet",collection: @tweets
          = paginate @tweets
  .main-right
    = render partial: "layouts/profile", locals: {user: @user}